fix: compilation failed
Zxilly/UA2F pull request #135
Opened 2024-09-04 15:43 UTC by SivonZn

在ubuntu22.04下，lede编译错误：

`ninja: Entering directory /home/sivon/lede/package/Sivon/UA2F/openwrt/../build'`
`[1/5] Building C object CMakeFiles/ua2f.dir/src/cache.c.o`
`FAILED: CMakeFiles/ua2f.dir/src/cache.c.o`
`/home/sivon/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/bin/mipsel-openwrt-linux-musl-gcc -DUA2F_ENABLE_UCI=1 -DUA2F_GIT_BRANCH=\"\" -DUA2F_GIT_COMMIT=\"90c9d9f5edce00a6d79847f5249eb1fdf68de929\" -DUA2F_GIT_TAG=\"v4.8.2\" -DUA2F_USE_CUSTOM_UA=1 -DUA2F_VERSION=\"4.8.2\" -I/home/sivon/lede/package/Sivon/UA2F/build -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -fmacro-prefix-map=/home/sivon/lede/package/Sivon/UA2F/openwrt/..=.. -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -ffunction-sections -fdata-sections -DNDEBUG -std=gnu17 -MD -MT CMakeFiles/ua2f.dir/src/cache.c.o -MF CMakeFiles/ua2f.dir/src/cache.c.o.d -o CMakeFiles/ua2f.dir/src/cache.c.o -c /home/sivon/lede/package/Sivon/UA2F/src/cache.c`
`/home/sivon/lede/package/Sivon/UA2F/src/cache.c: In function 'check_cache':`
`/home/sivon/lede/package/Sivon/UA2F/src/cache.c:17:36: error: parameter name omitted`
` _Noreturn static void* check_cache(void*) {`
`                                    ^~~~~`
`ninja: build stopped: subcommand failed.`

2024-09-04 16:44 UTC, Zxilly commented
https://gcc.gnu.org/pipermail/gcc-cvs/2020-October/336068.html

省略参数名称是在C标准中被明确支持的

2024-09-04 17:14 UTC, SivonZn commented
我的工具链是在编译lede的过程中随之一起编译的，没有使用其它的工具链

2024-09-04 17:27 UTC, Zxilly commented
版本是？是官方还是第三方的发行版

2024-09-04 17:30 UTC, SivonZn commented
官方版，9月4号晚上9点半刚刚拉取编译的

2024-09-04 17:41 UTC, Zxilly commented
执行一下
```
/home/sivon/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/bin/mipsel-openwrt-linux-musl-gcc --version
```

2024-09-04 17:51 UTC, Zxilly requested changes

2024-09-04 17:51 UTC, Zxilly commented on src/cache.c
> +_Noreturn static void* check_cache(void* arg) {
```suggestion
_Noreturn static void* check_cache(void* arg __attribute__((unused))) {
```

2024-09-04 23:57 UTC, SivonZn commented
执行结果：
`mipsel-openwrt-linux-musl-gcc (OpenWrt GCC 8.4.0 r6835-e90fe2d90) 8.4.0`

2024-09-06 08:23 UTC, merged

2024-09-06 08:24 UTC, Zxilly commented
谢谢